// PDF report generation (PRD §12). Built on-demand from the stored screening
// snapshot and streamed straight to the HTTP response — never written to disk.
// Printer-safe formatting: bold + prefix symbols rather than colour (§12 note).
import PDFDocument from 'pdfkit';
import { formatDateTime } from '../utils/dates.js';

// Draw a bold horizontal rule across the content width at the current y position.
// Replaces the old box-drawing character string ('━'), which the standard
// Helvetica/WinAnsi font can't render — it showed up as garbage ("%&") in the PDF.
function hr(doc, weight = 1.5) {
  doc.moveDown(0.3);
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const y = doc.y;
  doc.save().lineWidth(weight).strokeColor('#000000').moveTo(left, y).lineTo(right, y).stroke().restore();
  doc.moveDown(0.6);
}

// match_type → how it renders. `possible` triggers the manual-review disclaimer.
const NACTA_STATUS = {
  NO_MATCH: { symbol: '[OK]', heading: 'NO RECORD FOUND IN NACTA' },
  NO_LIST_UPLOADED: { symbol: '[!]', heading: 'NO NACTA LIST UPLOADED' },
  CNIC_MATCH_NAME_CONFIRMED: { symbol: '[RECORD]', heading: 'RECORD FOUND — CNIC & NAME CONFIRMED', hit: true },
  CNIC_MATCH_NAME_UNCONFIRMED: { symbol: '[RECORD]', heading: 'RECORD FOUND — CNIC MATCH, NAME UNCONFIRMED', hit: true, possible: true },
  NAME_ONLY_MATCH: { symbol: '[REVIEW]', heading: 'POSSIBLE MATCH — NAME ONLY', hit: true, possible: true },
};
const UNSC_STATUS = {
  NO_MATCH: { symbol: '[OK]', heading: 'NO RECORD FOUND IN UNSC CONSOLIDATED LIST' },
  NO_LIST_UPLOADED: { symbol: '[!]', heading: 'NO UNSC LIST UPLOADED' },
  CONFIRMED_MATCH: { symbol: '[RECORD]', heading: 'RECORD FOUND IN UNSC CONSOLIDATED LIST', hit: true },
  POSSIBLE_MATCH: { symbol: '[REVIEW]', heading: 'POSSIBLE MATCH — MANUAL REVIEW REQUIRED', hit: true, possible: true },
};

function refNumber(id) {
  return `SCR-${String(id).padStart(6, '0')}`;
}

function heading(doc, text) {
  hr(doc);
  doc.font('Helvetica-Bold').fontSize(11).text(text);
  doc.font('Helvetica').fontSize(10).moveDown(0.3);
}

function field(doc, label, value) {
  doc.font('Helvetica-Bold').fontSize(10).text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(value ?? '—');
}

function renderNacta(doc, result, version) {
  heading(doc, 'SECTION A — NACTA PROSCRIBED PERSONS LIST');
  doc.fontSize(10).text(`Checked against: ${version || 'No list uploaded'}`);
  doc.moveDown(0.5);

  const status = NACTA_STATUS[result.match_type] || NACTA_STATUS.NO_MATCH;
  doc.font('Helvetica-Bold').text(`${status.symbol} ${status.heading}`);
  doc.font('Helvetica').moveDown(0.3);

  if (!status.hit) {
    doc.text('No entry matching this CNIC or name/father combination was found.');
  } else {
    (result.records || []).forEach((r, i) => {
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').text(`Match ${i + 1}`);
      doc.font('Helvetica');
      field(doc, '  Full Name', r.full_name);
      field(doc, '  Father Name', r.father_name);
      field(doc, '  CNIC', r.cnic);
    });
  }
  if (status.possible) reviewDisclaimer(doc);
  doc.moveDown(0.5);
}

function renderUnsc(doc, result, version) {
  heading(doc, 'SECTION B — UNSC CONSOLIDATED LIST');
  doc.fontSize(10).text(`Checked against: ${version || 'No list uploaded'}`);
  doc.moveDown(0.5);

  const status = UNSC_STATUS[result.match_type] || UNSC_STATUS.NO_MATCH;
  doc.font('Helvetica-Bold').text(`${status.symbol} ${status.heading}`);
  doc.font('Helvetica').moveDown(0.3);

  if (!status.hit) {
    // The 3-check rule (name + DOB year + ID) is strict — be clear that NO_MATCH
    // here means "no entry passes all three" rather than "person not on list."
    doc.text(
      'No entry passes the strict three-check (name, year of birth, and identification number) verification.',
    );
  } else {
    (result.records || []).forEach((r) => {
      doc.moveDown(0.3);
      field(doc, '  Reference', r.ref_code);
      field(doc, '  Primary Name', r.primary_name);
      field(doc, '  Aliases', (r.aliases || []).join('; ') || '—');
      field(doc, '  Date of Birth', r.dob);
      field(doc, '  Nationality', r.nationality);
      field(doc, '  ID Numbers', (r.identification_numbers || []).join('; ') || '—');
      field(doc, '  Designation', r.designation);
      field(doc, '  Listed on', r.listed_on);
      if (r.pakistan_link) field(doc, '  Pakistan Link', r.pakistan_link); // informational only
      if (typeof r.match_score === 'number') {
        field(doc, '  Name Match Score', `${Math.round(r.match_score * 100)}%`);
      }
    });
  }
  if (status.possible) reviewDisclaimer(doc);
  doc.moveDown(0.5);
}

function reviewDisclaimer(doc) {
  doc.moveDown(0.3);
  doc.font('Helvetica-Oblique').fontSize(9)
    .text('Results marked "Possible Match" are generated by automated fuzzy matching and require manual verification by a qualified compliance officer before any action is taken.');
  doc.font('Helvetica').fontSize(10);
}

/**
 * Stream a screening report as application/pdf into `res`.
 * @param {import('express').Response} res
 * @param {object} screening row from screeningService.getScreening
 * @param {{ disposition?: 'inline'|'attachment' }} [opts] 'inline' opens in a tab
 *        (UI); 'attachment' forces a file download (external API).
 */
export function streamReport(res, screening, { disposition = 'inline' } = {}) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `${disposition}; filename="${refNumber(screening.id)}.pdf"`);
  doc.pipe(res);

  // Header — branded with the firm name on top
  hr(doc, 2);
  doc.font('Helvetica-Bold').fontSize(22).text('KTRADE SECURITIES LIMITED', { align: 'center' });
  doc.moveDown(0.15);
  doc.font('Helvetica-Bold').fontSize(13).text('Compliance Screening Report', { align: 'center' });
  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(10)
    .text(`Report Ref: ${refNumber(screening.id)}`, { align: 'center' })
    .text(`Screened on: ${formatDateTime(screening.screened_at)}`, { align: 'center' });
  hr(doc, 2);

  // Subject details
  doc.font('Helvetica-Bold').fontSize(11).text('SUBJECT DETAILS');
  doc.fontSize(10).moveDown(0.3);
  field(doc, 'Full Name', screening.input_full_name);
  field(doc, "Father's Name", screening.input_father_name);
  field(doc, 'CNIC', screening.input_cnic);
  field(doc, 'Date of Birth', screening.input_dob);
  doc.moveDown(0.5);

  renderNacta(doc, screening.nacta_result_json, screening.nacta_list_version);
  renderUnsc(doc, screening.unsc_result_json, screening.unsc_list_version);

  // Footer
  hr(doc, 2);
  doc.font('Helvetica').fontSize(9)
    .text('DISCLAIMER: This report is generated by an automated screening tool. Possible matches require manual verification by a qualified compliance officer before any action is taken.');
  hr(doc, 2);

  doc.end();
}
